name: Terraform Plan
on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'GCP Project ID'
        required: true
        type: string
      gcp_credentials:
        description: 'GCP Service Account JSON'
        required: true
        type: string
      microservice1_repo:
        description: 'Microservice 1 Git Repository URL'
        required: true
        type: string
      microservice2_repo:
        description: 'Microservice 2 Git Repository URL'
        required: true
        type: string
      tf_working_dir:
        description: 'Terraform working directory'
        default: '.'
        type: string

env:
  TF_VERSION: 1.5.0

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ github.event.inputs.gcp_credentials }}'
          project_id: '${{ github.event.inputs.gcp_project_id }}'

      - name: Terraform Init
        working-directory: ${{ github.event.inputs.tf_working_dir }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ github.event.inputs.tf_working_dir }}
        run: terraform validate

      - name: Terraform Format Check
        working-directory: ${{ github.event.inputs.tf_working_dir }}
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        working-directory: ${{ github.event.inputs.tf_working_dir }}
        run: |
          terraform plan \
            -var="gcp_project_id=${{ github.event.inputs.gcp_project_id }}" \
            -var="microservice1_repo=${{ github.event.inputs.microservice1_repo }}" \
            -var="microservice2_repo=${{ github.event.inputs.microservice2_repo }}" \
            -out=tfplan
        continue-on-error: false

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ github.event.inputs.tf_working_dir }}/tfplan
          retention-days: 1